version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://backend:8080  # 백엔드와 통신
    volumes:
      - ./frontend:/app  # 로컬 frontend 디렉토리를 컨테이너의 /app에 마운트
      - /app/node_modules  # node_modules는 볼륨에서 제외하여 충돌 방지

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/albasidae  # DB 컨테이너와 연결
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update  # DB 스키마 자동 업데이트
      - SPRING_DEVTOOLS_REMOTE_ENABLED=true  # DevTools 핫 리로딩 활성화
    depends_on:
      - db
    volumes:
    - ./backend/src:/app/src

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: albasidae  # 데이터베이스 이름을 albasidae로 설정
    ports:
      - "3306:3306"  # 호스트에서 3305 포트를 사용, 컨테이너 내에서는 여전히 3306 포트 사용
    networks:
      - app-network

networks:
  app-network:
